### PR TITLE
Fixes #9 -- adds support for fixed indices expressed in terms of codepoints instead of bytes

### LINKED ISSUE #9: Support for codepoint-based fixedwidth files
I have an extremely bonkers fixed-width file format where the file is utf-8 encoded, but the fixed offsets are expressed in decoded _codepoints_. Naturally this doesn't play super well with go-fixedwidth's (ENTIRELY REASONABLE) byte-based approach :-)

I'd like to find some way to shoe-horn this into go-fixedwidth (and obviously contribute this upstream).

I think the most efficient implementation is probably, if you're doing this codepoint mode, to conver the line to `[]rune` in `readLine` and in `rawValueFromLine` convert it back to a `[]byte` with the utf-8 value.

And I think that'd all work fine. But I don't see an obvious way to do this without throwing a bunch of `if` statements here and changing a bunch of types (e.g. I could replace all the `[]byte` with `struct { bytes []byte; runes []rune }` and then sticks `if` in `readLine` and `rawValueFromLine`).

Do you have an opinion on if there's a better implementation strategy? Would I be better off just forking `decode.go`?

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

File: decode.go [hunk 1]
```diff
@@ -117,6 +126,49 @@ func (d *Decoder) readLines(v reflect.Value) (err error) {
...
+}
+
+func newRawLine(bytes []byte, useCodepointIndices bool) (rawLine, error) {
+	line := rawLine{
+		bytes: bytes,
+	}
+	if useCodepointIndices {
+		bytesIdx := 0
+		codepointIdx := 0
+		// Lazily allocate this only if the line actaully contains a multi-byte
```
Comment (titanous) [inline decode.go]:
```suggestion
		// Lazily allocate this only if the line actually contains a multi-byte
```

File: decode.go [hunk 2]
```diff
@@ -117,6 +126,49 @@ func (d *Decoder) readLines(v reflect.Value) (err error) {
...
+		// character.
+		codepointIndices := []int(nil)
+		for bytesIdx < len(bytes) {
+			_, codepointSize := utf8.DecodeRune(bytes[bytesIdx:])
+			if codepointSize == 0 {
+				return rawLine{}, errors.New("Invalid codepoint")
```
Comment (titanous) [inline decode.go]:
```suggestion
				return rawLine{}, errors.New("fixedwidth: Invalid codepoint")
```

**Comment by alex** [comment]
Ok, I think I got all three points. Thanks for the quick review!
